### ISSUE TITLE
Test and deploy workflows failing due to `libffi.so.6` failing to load

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/iac#305]
## Describe the Bug
The test workflow is [failing](https://github.com/puppetlabs/iac/pull/303/checks?check_run_id=3400551245#step:5:55) with the following error:
```sh
bundler: failed to load command: jekyll (/github/workspace/vendor/gems/ruby/2.6.0/bin/jekyll)
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /github/workspace/vendor/gems/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi_c.so
  /github/workspace/vendor/gems/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `require'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `require'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `require'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `require'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `require'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
  /github/workspace/vendor/gems/ruby/2.6.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
  /github/workspace/vendor/gems/ruby/2.6.0/bin/jekyll:23:in `load'
  /github/workspace/vendor/gems/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
/entrypoint.rb:7:in `exit': no implicit conversion from nil to integer (TypeError)
	from /entrypoint.rb:7:in `system_or_fail'
	from /entrypoint.rb:15:in `<main>'
```

## Expected Behaviour
The workflows complete without errors

## Steps to Reproduce
Create a PR to the `puppetlabs/iac` repo

```sh
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210816.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210816.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210816.1
Virtual Environment Provisioner
  1.0.0.0-master-20210802-2
  ```

## Additional Context
- Ubuntu 18.04 seems to have this issue too: https://github.com/puppetlabs/iac/runs/3401795073#step:5:55
- Building the [this Docker image](https://github.com/DavidS/jekyll-deploy/blob/efb6045733158a09af0a86d5bb730ae8f594929a/deployer/Dockerfile) and running the `bundle` commands locally, seems to be working OK.
- [Ubuntu 20.04](https://github.com/actions/virtual-environments/tree/ubuntu20/20210816.1) and [Ubuntu 18.04](https://github.com/actions/virtual-environments/tree/ubuntu18/20210816.1) images were recently updated on Github Actions

**Comment by sanfrancrisko** [comment]
Temporary fix in #306 , but we should reintroduce the gem caching to the workflows again soon
